title: Constantina "Connie" Scoullis
email: scoullisconstantina@gmail.com
description: Connie Scoullis's website

url: "https://constantina-js.github.io"
baseurl: "/website-qa"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

collections:
  tags:
    output: true