title: Constantina "Connie" Scoullis
email: scoullisconstantina@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Connie Scoullis's website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https:///constantina.info" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  constantina-js

# Build settings
theme: minima
plugins:
  - jekyll-feed

paginate: 10
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate

collections:
  tags:
    output: true